### ISSUE TITLE
Use Prose.io for editing

### ISSUE THREAD

**Issue by patcon** [DISIC/politique-de-contribution-open-source#119]
Oh man, just had this page shared with me, and I really appreciate it!
https://disic.github.io/politique-de-contribution-open-source/en/gouvernance/

I love that you make the "suggest edit" button prominently available :)

I wanted to make a small suggestion for consideration. Right now, this button directs to:
https://github.com/DISIC/politique-de-contribution-open-source/edit/EnglishVersion/gouvernance.en.md

For those without access, that page has great instructions, but there is a small extra step of forking.

I was going to suggest that the French Government investigate either 1) using hosted Prose.io, or 2) self-hosting it's own version (since it's open source). This would allow the button to link here:
https://prose.io/#DISIC/politique-de-contribution-open-source/edit/EnglishVersion/gouvernance.en.md

The bonus side of using this tool is that, if you really like it, you can move to self-hosting, at which point you can start customizing it to the needs of public servants. For example, it could offer extra interface elements for GitHub users who are members of government GitHub organizations, to sidestep any pitfalls that are unique to public servants.

Anyhow, thanks very much for considering! I'm always eager to hear your thoughts, in case I end up having conversations with public servants in Canada :)

**Comment by bzg** [comment]
Hi @patcon, thanks for your feedback! I know prose.io and I use it for some side-projects, it is neat and useful. For this particular repository, we know most contributors and they are at ease with using Git or the github.com interface directly, so I don't think we should go the extra mile of requiring them to create an account on https://prose.io for now - but we'll keep this in mind and suggest the idea in our next meeting!

If you have conversations with public servants in Canada, please get in touch with us :)

**Comment by patcon** [comment]
Gotcha. No account though! Just login with GitHub. But yes, one more button click the first time. (which I don't mean to say is trivial)

**Comment by bzg** [comment]
Yes, you're right, I meant the "authorize on github" step. For some reason, prose.io won't accept commit for me right now (I tested on another repo, it worked fine.)  I'll investigate when I have more time.  Thanks!
