### ISSUE TITLE
Référencer etalab/data-codes-sources-fr dans le README

### ISSUE THREAD

**Issue by AntoineAugusti** [DISIC/politique-de-contribution-open-source#125]
Le fichier [OrgAccounts](https://github.com/DISIC/politique-de-contribution-open-source/blob/master/OrgAccounts) est utilisé par https://github.com/etalab/data-codes-sources-fr pour récupérer les métadonnées des organisations listées dans ce fichier.

Il serait utile de mentionner l'existence de ce répertoire dans le README

**Comment by bzg** [comment]
Fait, merci !
