### ISSUE TITLE
Identification des communautés prioritaires pour lesquelles un CLA est nécessaire

### ISSUE THREAD

**Issue by ljoubert** [DISIC/politique-de-contribution-open-source#13]
Comme évoqué dans la page :
https://github.com/DISIC/politique-de-contribution-open-source/blob/master/Ouverture.md#pré-autorisation-de-signer-un-icla-auprès-de-certaines-communautés

quelles seraient les communautés / entreprises avec lesquelles vous auriez un besoin de CLA corporate ?

 * Apache Software Foundation : https://www.apache.org/licenses/cla-corporate.txt
 * Eclipse Software Foundation : https://www.eclipse.org/legal/ecafaq.php
 * OASIS OPEN : https://www.oasis-open.org/resources/open-repositories/cla/entity-cla
 * Pivotal : https://cla.pivotal.io/
 * Ubuntu : https://www.ubuntu.com/legal/contributors
 * Google: https://cla.developers.google.com/clas

**Comment by luceole** [comment]
Pour nous Ubuntu en priorité et j'ajouterais bien 

- Samba: https://www.samba.org/samba/devel/copyright-policy.html
- Open Nebula: https://opennebula.org/community/contribute/

**Comment by camillem** [comment]
Django : https://www.djangoproject.com/foundation/cla/

**Comment by bzg** [comment]
Hello @luceole : finalement est-ce que le besoin d'un CLA avec Ubuntu et Open Nebula est remonté depuis ?

Je pose la question car il y a un cas de CLA signé par un organisme public, je vais bientôt proposer une reformulation de la politique de contribution à ce sujet.
