### ISSUE TITLE
Répertoire numerique.gouv.fr

### ISSUE THREAD

**Issue by AntoineAugusti** [DISIC/politique-de-contribution-open-source#135]
Bonjour,

Les fichiers Markdown de la POCOS sont aussi présents sur le répertoire `numerique-gouv/numerique.gouv.fr` : https://github.com/numerique-gouv/numerique.gouv.fr/tree/master/_politique-logiciel-libre.

Les issues doivent-elles être ouvertes ici ?

**Comment by bzg** [comment]
Bonjour ! Oui, elles doivent bien être ouvertes ici.
