### ISSUE TITLE
Pratique : Inventaire des comptes d'organisation

### ISSUE THREAD

**Issue by AntoineAugusti** [DISIC/politique-de-contribution-open-source#139]
La page pratique, section "Inventaire des comptes d'organisation" mentionne le fait de s'inscrire sur GitHub governments et de se rajouter à https://github.com/github/government.github.com/blob/gh-pages/_data/governments.yml.

Il existe également un fichier [OrgAccounts](https://github.com/DISIC/politique-de-contribution-open-source/blob/master/OrgAccounts) dans ce répertoire, qui semble être le plus utilisé.

Par ailleurs, un inventaire des dépôts de code est construit automatiquement à partir de ce fichier dans le répertoire https://github.com/etalab/data-codes-sources-fr.

Questions :
- Faut-il toujours se référencer sur GitHub governments ?
- Il me parait utile de demander aux personnes de s'ajouter dans `OrgAccounts`
- Peut-on dès à présent mentionner le répertoire https://github.com/etalab/data-codes-sources-fr ?

**Comment by bzg** [comment]
> Faut-il toujours se référencer sur GitHub governments ?

**Oui**.

> Il me parait utile de demander aux personnes de s'ajouter dans OrgAccounts

**Oui**, bonne idée. Au passage, je serais pour renommer `OrgAccounts` en `comptes-organismes-publics`: nous nous adressons à tous les organismes publics, et en français.

> Peut-on dès à présent mentionner le répertoire https://github.com/etalab/data-codes-sources-fr ?

Non. À ce stade il n'est pas très utile pour les lecteurs de la Politique de contribution Open Source.

Je pense que ce sera utile quand nous aurons fait deux choses: (1) bien homogénéisé `OrgAccounts` pour qu'il n'y ait que des comptes d'organisation et (2) collecté les informations des différentes forges dans `data-codes-sources-fr`.

WDYT?

**Comment by AntoineAugusti** [comment]
Pas de problème pour renommer en français. Quand ce sera fait, je veux bien un ping pour mettre ça downstream.

Je suis bien évidemment en faveur d'une homogénéisation des comptes et d'une collecte élargie, c'est d'ailleurs prévu (https://github.com/etalab/data-codes-sources-fr/issues/3, https://github.com/etalab/data-codes-sources-fr/issues/4) mais prendra du temps.

**Comment by olivier-maury** [comment]
La forge de l'enseignement supérieur et recherche (ESR) est SourceSup. Comment comptez-vous collecter les informations ?

Par exemple, voici des URL pour lister les projets pour l'INRA :

* https://sourcesup.renater.fr/softwaremap/project_by_etab.php?id_etab=C190&submit=Soumettre
* https://sourcesup.renater.fr/softwaremap/project_by_etab.php?id_etab=S45&submit=Soumettre
* https://sourcesup.renater.fr/softwaremap/project_by_etab.php?id_etab=S13&submit=Soumettre
* https://sourcesup.renater.fr/softwaremap/project_by_etab.php?id_etab=S26&submit=Soumettre
* https://sourcesup.renater.fr/softwaremap/project_by_etab.php?id_etab=S32&submit=Soumettre

**Comment by bzg** [comment]
Nous avons échangé avec l'équipe de https://www.softwareheritage.org pour voir comment collecter les métadonnées des dépôts d'instance FusionForge. Ils ont une solution pour l'instance FusionForge de l'Adullact, via un module spécifique (nommé, je crois, `repositories`). 

Si le FusionForge de renater.fr utilisait ce module ou équivalent, cela nous faciliterait la tâche: savez-vous si c'est le cas?

Sinon, peut-être pourriez-vous vous rapprocher de Software Heritage pour voir comment le mettre en place?

**Comment by olivier-maury** [comment]
Je ne saurais vous dire, je ne suis qu'utilisateur de la forge. Vous pouvez contacter le support mentionné sur la page d'accueil de SourceSup.

**Comment by bzg** [comment]
Merci. Je le ferai quand nous aurons le temps de collecter les données sur cette forge.

**Comment by bzg** [comment]
Une partie de l'issue est résolue, l'autre, celle concernant la collecte d'information depuis les instance de FusionForge est dans [cette issue](https://github.com/etalab/data-codes-sources-fr/issues/6).
