### ISSUE TITLE
Utilisation de pullapprove

### ISSUE THREAD

**Issue by ljoubert** [DISIC/politique-de-contribution-open-source#14]
Pour mettre en oeuvre automatiquement les principes de gouvernance retenus dans https://github.com/DISIC/politique-de-contribution-open-source/blob/master/Gouvernance.md seriez-vous d'accord pour utiliser l'outil pullapprove.com ?

**Comment by bzg** [comment]
Je propose qu'on reste en mode manuel pour l'instant. Si l'implication collective sur l'approbation l'exige, nous pourront tester pullapprove.com plus tard.
