### ISSUE TITLE
Lien relref nons fonctionnels sur le site

### ISSUE THREAD

**Issue by pajachiet** [DISIC/politique-de-contribution-open-source#147]
Des liens relref ne sont pas fonctionnels. Ils ajoutent le nom de leur page courante (il me semble pour toute les pages, sauf celle d'introduction).

Plusieurs exemples sur la page faq : https://www.numerique.gouv.fr/publications/politique-logiciel-libre/faq/

Pour lister les premiers de chaque page : https://github.com/DISIC/politique-de-contribution-open-source/search?q=relref&unscoped_q=relref

**Comment by bzg** [comment]
Merci d'avoir signalé le problème.
