### ISSUE TITLE
Comment utiliser un DCO en pratique ?

### ISSUE THREAD

**Issue by pajachiet** [DISIC/politique-de-contribution-open-source#148]
La section qui décrit le DCO me parait incomplète https://www.numerique.gouv.fr/publications/politique-logiciel-libre/pratique/.

- Comment le mettre en pratique dans le cadre d'un projet ? 
- S'agit-il de le faire signer en amont une fois pour toute ? de le demander à chaque contribution importante ? 
- Quel est le lien avec le sign-off  de git ?

**Comment by bzg** [comment]
Quelques éléments avant de faire une éventuelle PR:

> Quel est le lien avec le sign-off de git ?

Le sign-off de Git est utilisé comme indication que le contributeur accepte le DCO: pour forcer le DCO et le sign-off sur une branche d'un dépôt, voir [ces explications](https://wiki.linuxfoundation.org/dco).

> S'agit-il de le faire signer en amont une fois pour toute ? de le demander à chaque contribution importante ?

Pour chaque contribution, importante ou pas.

> Comment le mettre en pratique dans le cadre d'un projet ?

Soit les contributeurs ont l'habitude d'utiliser `git commit -s`, soit il faut leur rappeler. Chaque projet peut ensuite avoir, selon ses exigences, une tolérance plus ou moins large sur les commits non signés.

- https://stackoverflow.com/questions/1962094/what-is-the-sign-off-feature-in-git-for
- https://opensource.com/article/18/3/cla-vs-dco-whats-difference
