### ISSUE TITLE
Faire évoluer le format de `comptes-organismes-publics`

### ISSUE THREAD

**Issue by bzg** [DISIC/politique-de-contribution-open-source#162]
1. `mv comptes-organismes-publics comptes-organismes-publics.yml`

2. Utiliser `org_account_url` et `forge` comme informations élémentaires pour chaque entrée, par exemple:

```
- org_account_url: https://framagit.org/parcoursup
  forge: gitlab
  
- org_account_url: https://github.com/ANSSI-FR
  forge: github
```

Le but est de permettre de savoir quelle est l'API à utiliser (si elle existe) pour les données collectées depuis [ce dépôt](https://github.com/etalab/data-codes-sources-fr).

@ljoubert et @AntoineAugusti OK pour vous ?

**Comment by ljoubert** [comment]
Hello, why not, mais sur le fond la forge s'identifie au niveau du domaine et non de l'URL, ca risque d'être contraignant de le spécifier à chaque ligne. Possible de faire un fichier "forge" complémentaire qui explique que framagit c'est du gitlab ?

**Comment by bzg** [comment]
Oui, tu as raison. On ferait un fichier `forges.yml` avec par exemple

```
- platform: framagit.org
  forge: gitlab
- ...
```

@AntoineAugusti OK pour toi ?

**Comment by AntoineAugusti** [comment]
Ça me va. Les noms des clés sont à peaufiner : une URL n'est pas une plateforme et il y a un mélange français / anglais.

**Comment by bzg** [comment]
```
- domain_name: framagit.org
  forge: gitlab
```

Est-ce utile de récupérer la version de la forge et/ou la version de son API?
