### ISSUE TITLE
Forge Adullact

### ISSUE THREAD

**Issue by ljoubert** [DISIC/politique-de-contribution-open-source#168]
La forge adullact est entièrement listée dans le fichier comptes-organismes-publics: Il faudrait pour moi cibler les comptes d'organisation.
https://gitlab.adullact.net

**Comment by bzg** [comment]
Pour mémoire, nous avons ce problème pour les liens suivants:

- https://dev.ch-poitiers.fr (GitLab)
- https://git.unistra.fr (GitLab)
- https://gitlab.inria.fr (GitLab)
- https://sourcesup.renater.fr (FusionForge)
- https://gforge.inria.fr (FusionForge)

@AntoineAugusti et moi étions partis du principe que tous les comptes d'organisation de ces forges (plutôt nommés "Groupes" sur GitLab et FusionForge) étaient des comptes d'organismes publics ou rattachés à des organismes publics: n'est-ce pas le cas?

**Comment by AntoineAugusti** [comment]
C'était le parti pris dans cette implémentation : https://github.com/etalab/data-codes-sources-fr/pull/23. Pour certaines forges, on ne liste pas les différentes organisations (potentiellement des dizaines / centaines), mais on trouve automatiquement les organisations sur la plateforme et on récupère leurs informations.

**Comment by ljoubert** [comment]
Autant cela ne me pose pas de question pour des établissement publics où la forge en entier peut être considérée. Cela m'interpelle plus pour l'adullact qui meme avec sa mission ne peut pas, à mon sens, être considérée comme une forge exclusive de projets d'organisme public. Dans ce cas précis, il faudrait pouvoir distinguer les comptes d'organisation, au même titre que github et gitlab. Après je conçois que dans un premier temps cela peut être couteux et qu'on peut rester dans un premier temps dans cette situation.

**Comment by AntoineAugusti** [comment]
La problématique de l'Adullact est loin d'être résolue car c'est du Fusion Forge avec une API SOAP. https://github.com/etalab/data-codes-sources-fr/issues/6

**Comment by bzg** [comment]
La discussion se poursuit [ici](https://github.com/DISIC/politique-de-contribution-open-source/issues/179).
