### ISSUE TITLE
Ajouter une notion de "référent technique" par ministère

### ISSUE THREAD

**Issue by bzg** [DISIC/politique-de-contribution-open-source#170]
Un ministère peut publier du code source sur plusieurs comptes d'organisation d'une forge, voire plusieurs forges.

Il serait utile que la politique de contribution open source propose de désigner un référent technique capable de répondre, au sein d'un ministère, à la question : « Où publier mon code source ? », sans avoir pour cela à instancier une politique distincte.

**Comment by ljoubert** [comment]
Bonjour,

c'est le cas, les référents sont listés dans le fichier MAINTAINERS: https://github.com/DISIC/politique-de-contribution-open-source/blob/master/MAINTAINERS qui pourront rediriger si nécessaire.

Si tu penses que c'est suffisant, cela peut être intéressant de rajouter une entrée à la FAQ.

**Comment by bzg** [comment]
Hello, ce n'est pas clair dans le texte actuel.

Les personnes listées dans le fichier `MAINTAINERS` sont présentées comme les mainteneurs de la politique de contribution, pas forcément comme les personnes à laquelle un agent doit s'adresser quand il veut savoir où publier un nouveau code source.

Je pense apporter la précision dans "Gestion des comptes personnels et d’organisation".

WDYT?
