### ISSUE TITLE
Don't include all of gitlab.adullact.net

### ISSUE THREAD

**Issue by bzg** [DISIC/politique-de-contribution-open-source#179]
https://gitlab.adullact.net is the host for many projects, some of them being initiated by the public sector, some of them not. I suggest we only include GitLab projects that are initiated by public organizations, not the whole forge.

@ljoubert @AntoineAugusti WDYT?

**Comment by AntoineAugusti** [comment]
LGTM

**Comment by mfaure** [comment]
@bzg Gitlab.adullact.net is dedicated to local governments software. Do you have example of "non-gov" software? Had you ever found some exceptions, I think they should not change your default policy :)

**Comment by bzg** [comment]
Hi @mfaure and thanks for your feedback. The primary intent of code.etalab.gouv.fr is to list source code _published by_ the public sector, not _made for_ or _related/dedicated to_ the public sector - that's why `comptes-organismes-publics` is named that way.

For example, it is fine to reference [prodigeadmin](https://gitlab.adullact.net/prodigeadmin) because, by reading the description, I assume it is handled by the CEREMA, which is public sector. But [pixelhumain](https://gitlab.adullact.net/pixelhumain) or [Libriciel](https://gitlab.adullact.net/Libriciel) are not handled by a public administration, they are respectively handled by an association (or a community?) and a company.

Is this criterium clear and "actionable" enough for you?

Could you help us sort out GitLab projects owned by an administration (i.e. where the admin of the project is from the public sector) from projects owned by a company or an (informal) association?

Thanks again for your help, clarity is very important here.

**Comment by mfaure** [comment]
Thanks @bzg for the explanations. Feel free to ping us if you need help

**Comment by bzg** [comment]
Ping :)

We need help identifying what GitLab projects are administrated by public organizations on https://gitlab.adullact.net

I suspect this is not straightforward and requires quite some time on your side... So I suggest that you first help us identifying the 10 most important projects for now, then add them in `comptes-organismes-publics` and remove the gitlab.adullact.net there.

**Comment by bzg** [comment]
Hi @mfaure, I plan to publicly advertize the existence of https://code.etalab.gouv.fr on wednesday Oct. 2dn on Etalab's blog.

I think the safe way to deal with this issue is to remove `gitlab.adullact.net` from `comptes-organismes-publics` for now, then add specific projects progressively.

Are you okay with this approach?

I'd rather _add_ links to repos than _delete_ them: there is less to explain to our users.
