### ISSUE TITLE
[pratique.md] système de suivi de version != plate-forme

### ISSUE THREAD

**Issue by AnneCav** [DISIC/politique-de-contribution-open-source#18]
Sur la page pratique.md, dans la liste résumée, le premier point mentionne  : 

> * Utilisation nécessaire d'un système de suivi de version distribué (git, bitbucket, mercurial) 

Or Bitbucket est le nom d'une plate-forme (comme github ou gitlab par exemple) mais pas un système de suivi.

Je suggère de supprimer Bitbucket de cette phrase.

**Comment by AnneCav** [comment]
Idem un peu plus loin dans la même page.

**Comment by ljoubert** [comment]
Effectivement, il y a confusion avec Bitkeeper, merci beaucoup
