### ISSUE TITLE
Include all of gitlab.inria.fr?

### ISSUE THREAD

**Issue by bzg** [DISIC/politique-de-contribution-open-source#180]
Are all groups and projects on `gitlab.inria.fr` owned and managed by public sector actors?

Or are we in a similar situation than for [Adullact](https://github.com/DISIC/politique-de-contribution-open-source/issues/179)?

**Comment by bzg** [comment]
Hi @neurolit I'm about to close this issue, assuming all groups collected from `gitlab.inria.fr` are owned by a pulic agent (not by an association or a company) with code that is published as `open data` (with or without a free software license).

Can you confirm this is the case? Or are there groups that are really owned by private companies (e.g. in the context of privately funded developments)?

Thanks for your feedback!

**Comment by neurolit** [comment]
Hi @bzg! Let me investigate this issue, I'll give you an answer in a few days.

**Comment by bzg** [comment]
Hi @neurolit, did you have a chance to have a look at this? Thank you!

**Comment by bzg** [comment]
Hi @neurolit there are way to many INRIA groups that should not be listed on https://code.etalab.gouv.fr - can you think of a good way to exclude them? Or shall we list groups that _should_ be included?

Thanks!

**Comment by neurolit** [comment]
Hi @bzg, we can't assume that all groups collected from ```gitlab.inria.fr``` are owned by a public agent (not by an association or a company) with code that is published as *open data* (with or without a free software license).

We are planning to set a policy about public repositories in our Gitlab instance.

Maybe we could maintain a list of "official" groups, used by ```code.etalab.gouv.fr```?

**Comment by bzg** [comment]
Hi @neurolit, thanks for your answer. 

> Maybe we could maintain a list of "official" groups, used by code.etalab.gouv.fr?

Yes, I think this is the best way to deal with the many groups you have, and this is what we do with `gitlab.adullact.net` too. You can send this list in this issue or just send it by email.

**Comment by bzg** [comment]
Hi @neurolit, happy new year!  I guess you've been busy with other things. Let me know if I can somehow ease the process of picking up the right official groups. Thanks,

**Comment by neurolit** [comment]
@bzg Hi! Happy new year for you too!
We are preparing a list of our official groups, we'll publish a JSON file on our Gitlab instance, and I'll post the URL here. Is it OK for you?

**Comment by bzg** [comment]
Yes, that's perfect, thanks a lot!

**Comment by neurolit** [comment]
@bzg Here we are: the first list of repositories which _should_ be included is available [at the following address](https://gitlab.inria.fr/dsi_public/depots_officiels_inria_gitlab/raw/master/code_etalab/inria_gitlab_public_repositories.json). We will update this file when new repositories will be published.

**Comment by bzg** [comment]
Hi @neurolit, thanks for the list. The file [comptes-organismes-publics](https://github.com/DISIC/politique-de-contribution-open-source/blob/master/comptes-organismes-publics) only lists GitHub organizations or GitLab groups, it does not list repositories.

Based on your `json` file, is it safe to add these groups?

- https://gitlab.inria.fr/coquelicot/
- https://gitlab.inria.fr/dsi_public/
- https://gitlab.inria.fr/vidjil/
- https://gitlab.inria.fr/openvibe/
- https://gitlab.inria.fr/openvibe/

If we add all these groups, `code.etalab.gouv.fr` will list _all_ repositories from the groups above, which I think is safe, as long as the groups are actually managed by public agents.

Go?

**Comment by bzg** [comment]
Note that groups with public code on `gitlab.inria.fr` don't need to be "officially" validated by INRIA for their source code to fall under the loi pour une République numérique and to be legally considered as _open data_.

**Comment by bzg** [comment]
Just to be clear: I'd rather have the list of groups to be as inclusive as possible. 

We should only exclude groups that are not managed by a public agent and where code intellectual property is not fully or clearly owned by INRIA.

Let me know when you have an update - thanks!

**Comment by bzg** [comment]
Hi @neurolit, I'm just waiting for your "go" - can I proceed as explained above? Don't hesitate to give me a call if needed.
