### ISSUE TITLE
[pratique.md] Reliquat de la version UK ?

### ISSUE THREAD

**Issue by AnneCav** [DISIC/politique-de-contribution-open-source#19]
Le chapitre : Inventaire des comptes d'organisation comporte des liens/bonnes pratiques qui ne peuvent s'appliquer pour nous car propres à la Grande-Bretagne. À moins qu'on souhaite réellement que les contributeurs s'inscrivent sur le compte gouvernemental britannique ? ;-)

**Comment by ljoubert** [comment]
Je ne comprends pas votre remarque sur le gouvernement britannique. Pouvez-vous être plus spécifique ? Pour Github, il y a une liste de tous les pays, avec pour la France:

France:
  - afimb
  - ANSSI-FR
  - ApieFrance
  - communaute-cimi
  - DGFiP
  - diplomatiegouvfr
  - disic
  - erasme
  - etalab
  - nanterre
  - polewebmaedi
  - ProgrammeVitam
  - sgmap
 - sgmap-agd

**Comment by AnneCav** [comment]
Bonjour,

Voici le passage en question : 

> Spécifiquement pour Github, référencer le compte d'organisation comme un compte gouvernemental
>  * Inscrivez vous si ce n'est pas déjà fait dans la communauté [https://github.com/government/welcome](https://github.com/government/welcome)
 >  * Référencez votre compte d'organisation en l'ajoutant sur la page : [https://github.com/github/government.github.com/blob/gh-pages/_data/governments.yml](https://github.com/github/government.github.com/blob/gh-pages/_data/governments.yml) conformément à la page [https://government.github.com/community/](https://government.github.com/community/)

Ah... je viens de comprendre en relisant soigneusement la page cible (c'est super pas clair je trouve, mébon.)

**Comment by ljoubert** [comment]
Bonjour Anne, je te propose de soumettre une PR de clarification si besoin. Je propose de clore l'issue, n'hésite pas à la rouvrir si besoin.
