### ISSUE TITLE
Indiquer le lien avec code.etalab.gouv.fr dans le README

### ISSUE THREAD

**Issue by pachevalier** [DISIC/politique-de-contribution-open-source#206]
Est-ce que ce ne serait pas intéressant de préciser dans le README que ce fichier permet d'alimenter code.etalab.gouv.fr ?

**Comment by bzg** [comment]
J'en ai profité pour ajouter un lien vers [la page du jeu de données](https://www.data.gouv.fr/fr/datasets/inventaire-des-depots-de-code-source-des-organismes-publics/) et le [guide interactif](https://guide-juridique-logiciel-libre.etalab.gouv.fr/).

Merci pour la suggestion!
