### ISSUE TITLE
Recommandation de licences

### ISSUE THREAD

**Issue by fbeauchamp** [DISIC/politique-de-contribution-open-source#22]
Bonjour, 

[Recommandation d’utiliser des licences permissives dans le cas général](https://disic.github.io/politique-de-contribution-open-source/ouverture/#recommandation-d-utiliser-des-licences-permissives-dans-le-cas-général) 

Je pense qu'il pourrait être utile de donner quelques exemple de licences permissives ( Cecil, BSD) et quelques exemple de licences à l'identique (Creative Commons,...)  pour mieux illustrer le propos. 

Serait il aussi possible de préciser le rôle de conseil ou d'accompagnement que pourrait prendre la DINSIC en cas de conflit sur une licence ? Savoir que des spécialistes pourraient aider en cas d'usage incompatible avec la licence choisie pourrait rassurer les administrations 

Merci

**Comment by ljoubert** [comment]
Les licences sont fixées par décret dans le paragraphe précédent et regroupées par famille: 
 * http://www.data.gouv.fr/fr/licences
Nous ne voulions pas dupliquer l'information en la copiant dans la politique. 

Est-ce que cela vous convient ?
