### ISSUE TITLE
Trier le niveau de recommendation dans pratique.md

### ISSUE THREAD

**Issue by archiloque** [DISIC/politique-de-contribution-open-source#24]
Suggestion : dans https://github.com/DISIC/politique-de-contribution-open-source/blob/master/pratique.md mettre d’abord les éléments obligatoires, puis les éléments recommandés, puis les suggestions, et possiblement le mettre en avant dans les titres des chapitres

**Comment by bzg** [comment]
Merci pour la suggestion. Pourriez-vous faire une première passe, même approximative, pour que je me rende compte du résultat? Merci!

**Comment by bzg** [comment]
Bonjour @archiloque : la version 1.1 est sortie, nous préparons la `v1.2` qui pourrait sortir d'ici juin 2020. Si tu vois comment avancer sur cette PR, n'hésite pas.  Merci !

**Comment by bzg** [comment]
Pas de retour sur cette issue, je ferme.
