### ISSUE TITLE
Licences avec partage à l'identique

### ISSUE THREAD

**Issue by betaglop** [DISIC/politique-de-contribution-open-source#34]
Bonjour,

Vous conseillez d'utiliser des licences avec partage à l'identique pour un certain nombre de productions dans vos "principes d'ouverture"... Mais je ne trouve nulle part de référence aux licences concordantes.

Je pense bien à une CC ND (no derivative), mais celle-ci n'est surtout valable que pour les données ou du texte, pas vraiment pour des algorithmes (même si c'est envisageable, ce n'est pas très adapté).

En vous remerciant,

**Comment by ljoubert** [comment]
Faites-vous référence au décret qui liste les deux familles de licences dans le cas où l'administration à le choix de la licence : http://www.data.gouv.fr/fr/licences ?

**Comment by betaglop** [comment]
En effet, j'ai été un peu rapide : il y a bien l'OdBL, mais elle s'applique plus à des données qu'à des productions intellectuelles (textes ou algorithmes par exemple). Donc ma question reformulée serait plutôt "Je ne trouve pas de référence à des licences "avec partage à l'identique" autre que pour des données. En connaissez-vous ? Si oui, sont-elles référencées quelque part par la DINSIC ?

**Comment by bzg** [comment]
Bonjour Baptiste,

> "Je ne trouve pas de référence à des licences "avec partage à l'identique" autre que pour des données. En connaissez-vous ? Si oui, sont-elles référencées quelque part par la DINSIC ?

http://www.data.gouv.fr/fr/licences référence bien les licences avec obligation de réciprocité (ou « copyleft ») pour les codes sources des logiciels.  Ou alors je ne comprends pas bien la question ?

**Comment by betaglop** [comment]
Eh bien, je pense par exemple à la licence "partage à l'identique" pour des documents ou des œuvres d'art, comme la Créative Commons NoDerivative ([CC-BY-ND](https://creativecommons.org/licenses/by-nd/4.0/)).

**Comment by bzg** [comment]
Dans le cadre des licences Creative Commons, la notion de "Partage à l'identique" désigne la clause `ShareAlike`: voir par exemple la licence CC by-sa 3.0, dont le nom complet traduit en français est [Creative Commons Attribution Partage à l'Identique 3.0 France](https://creativecommons.org/licenses/by-sa/3.0/legalcode.fr).

Il s'agit de l'identité des conditions légales attachées à l'oeuvre, pas de l'identité de l'oeuvre en tant qu'objet.

Je ne sais pas s'il est prévu d'inclure la licence CC-BY-ND dans la liste des licences pouvant être utilisées par l'administration. Avez-vous un exemple particulier où cette licence vous paraîtrait pertinente ?

**Comment by betaglop** [comment]
ok je comprends... je vois maintenant plus clairement ma méprise alors.

J'ai du mal à travailler votre question car je n'aime pas trop les "no-derivative" et ne les utilise jamais (pro et perso). J'ai cependant lu parfois des textes à la CC-By-ND était appliquée. Il s'agissait souvent de textes ou d'études scientifiques. Je pense par exemple à une thèse de doctorat ou un article publié dans une revue à comité de lecture... dont l'auteur souhaiterait permettre la diffusion mais en respectant le contenu, privilégiant l'habitude scientifique de citer ses sources en y apportant une interprétation ou des modifications, plutôt que de les reproduire in extenso en les transformant, ce qui pourrait amener à des propos finaux incohérents avec ceux de l'auteur, tout en gardant la signature de l'auteur en bas (By).

**Comment by bzg** [comment]
La plupart des textes de Richard Stallman sont publiés sous licence CC-BY-ND 4.0. Par exemple [celui-ci](https://www.gnu.org/philosophy/not-ipr.fr.html). Il faut voir si cela peut avoir du sens avec certaines données, ce n'est pas exclu.

**Comment by ljoubert** [comment]
La licence équivalente retenue pour l'administration est la licence ouverte 2.0 qui est d'ailleurs celle retenue pour cette politique de contribution. Vous trouverez plus de détails : https://www.etalab.gouv.fr/licence-version-2-0-de-la-licence-ouverte-suite-a-la-consultation-et-presentation-du-decret

Celle-ci est explicitement compatible avec la CC-BY.

**Comment by ljoubert** [comment]
Fin de discussion probable. N'hésitez pas à rouvrir cette issue si ce n'était pas le cas.
