### ISSUE TITLE
Conseil très contestable dans « Développement sécurisé »

### ISSUE THREAD

**Issue by bortzmeyer** [DISIC/politique-de-contribution-open-source#36]
Le texte actuel des Meilleures Pratiques dit « Toutes les entrées externes (e.g. de l’utilisateur) doivent être filtrées en explicitant uniquement les cas acceptés (filtrage par liste blanche) avant leur manipulation/stockage » Il pose plusieurs problèmes.

1) Ce n'est pas au moment du stockage qu'il faut tester les données, c'est surtout au moment de leur utilisation. En effet, la dangerosité éventuelle des données dépend de leur utilisation. Un citoyen a le droit d'avoir une apostrophe dans son nom propre, cela ne pose pas de problème si on exporte la base vers HTML mais est dangereux si on le fait vers SQL. C'est donc au moment de l*utilisation* qu'il faut prendre des précautions.

2) Le cas des bases de données est particulièrement difficile car on ne peut pas savoir à l'avance toutes les utilisations qui en seront faites. Vouloir empêcher le stockage de données problématiques va probablement mener à des faux négatifs (on accepte des données qui poseront ensuite des problèmes, parce qu'une utilisation n'avait pas été prévue) et des faux positifs (on refuse des données légitimes, comme ces innombrables applications de l'administration qui me refusent mon prénom en prétendant qu'il comporterait un « caractère illégal »).

3) La constitution d'une liste blanche est une opération délicate. Parfois, on n'a pas de référence sur laquelle s'appuyer (où est le document légal qui donne la liste des caractères acceptés dans l'état-civil français ?). Parfois, on en a une mais les programmeurs ne la lisent pas (exemple des formulaires qui testent la syntaxe des adresses email, non pas à partir de la grammaire normalisée mais à partir de leurs propres suppositions sur la syntaxe d'une adresse). Si on maintient ce conseil, il faudrait au minimum ajouter que la liste blanche doit être un document de référence (et ne pas venir de l'imagination du programmeur), document qu'on doit suivre au pied de la lettre.

**Comment by bzg** [comment]
Je propose cette formulation:

> Toutes les entrées externes (e.g. de l’utilisateur) doivent être contrôlées avant leur stockage : si un référentiel pertinent existe, il sera utilisé comme liste blanche ; si aucun référentiel pertinent n’existe, les entrées excluront au moins les cas problématiques.

Est-ce que cela répondrait aux points soulevés ?  Si non, quelle autre proposition ?

**Comment by bortzmeyer** [comment]
Non, cela ne répond pas. Par exemple, l'état actuel du développement, c'est que quand il exste un référentiel pertinent, les développeurs ne le lisent pas (cf. vérification des adresses de courrier).  Et, surtout, cela fait tout à l'envers : c'est quand on utilise des données qu'il faut les contrôler, pas quand on les stocke.

**Comment by bzg** [comment]
Ma formulation n'évoque ni l'utilisation ni le stockage.

Est-ce que vous pouvez faire une proposition?

**Comment by revolunet** [comment]
Bonjour, pour tente d'avancer sur ce point, je vous proposer une variante :

> Toutes les entrées externes (e.g. de l’utilisateur) doivent être contrôlées et filtrées avant leur utilisation ou leur stockage, selon les bonnes pratiques de sécurité en fonction de leur destination.

> Exemples :
>  - l'utilisation de données pour requêter une base de données SQL devra utiliser la méthode de filtrage appropriée pour prévenir les [injections SQL](https://fr.wikipedia.org/wiki/Injection_SQL). (ex: module [pg-format](https://www.npmjs.com/package/pg-format))
> - l'affichage de HTML issu de données utilisateurs dans une page web devra filtrer le HTML pour éviter les attaque de type [XSS](https://fr.wikipedia.org/wiki/Cross-site_scripting). (ex: module [xss](https://www.npmjs.com/package/xss))

> Dans le cas de données associées à des référentiels existants, privilégier le recours à une "liste blanche" [lien vers les référentiels en open-data ou sous forme d'API]

> [lien vers bonnes pratiques dev+sécu de l'ANSSI]

**Comment by ljoubert** [comment]
La partie exemple me semble aller un peu loin dans le cadre de cette politique. Est-ce que la première phrase suffirait ? On pourrait se limiter à:

> Toutes les entrées externes (e.g. de l’utilisateur) doivent être contrôlées et filtrées avant leur utilisation selon les bonnes pratiques de sécurité en fonction de leur destination.

OK pour vous ?

**Comment by revolunet** [comment]
👍

**Comment by krominet** [comment]
le débat me semble légèrement abscons , le stockage étant une forme de d’utilisation d'une donnée ...

**Comment by bortzmeyer** [comment]
@krominet Le débat est très concret, au contraire. Actuellement, 99 % des développeurs se plantent : ils refusent des données parfaitement valides (noms avec des apostrophes, caractères composés, plus dans l'adresse) tout en ne prenant pas de précautions pour leur utilisation (SQL sans procédures préparées, HTML sans tenir compte du risque d'injection).

**Comment by ljoubert** [comment]
@krominet j'étais parti sur le même postulat en proposant
> Toutes les entrées externes (e.g. de l’utilisateur) doivent être contrôlées et filtrées avant leur utilisation selon les bonnes pratiques de sécurité en fonction de leur destination.

@bortzmeyer préférez-vous
> Toutes les entrées externes (e.g. de l’utilisateur) doivent être contrôlées et filtrées avant leur utilisation ou leur stockage, selon les bonnes pratiques de sécurité en fonction de leur destination.

**Comment by bortzmeyer** [comment]
@ljoubert Franchement, ce conseil est dangereux. Aujourd'hui, des tas de programmeurs amateurs filtrent n'importe comment les données en entrée et refusent des données légales (TLD de plus de 3 caractères, adresses de courrier avec des plus, noms de famille ayant des espaces ou des apostrophes, caractères non-ASCII, etc). Juste leur demander de filtrer est casse-gueule, à la fois insuffisant (on ne pense pas à tous les cas d'utilisation) et trop violent (on refuse des caractères sans bonne raison).

**Comment by krominet** [comment]
@bortzmeyer  
je pensait à un extrait de la loi I&L de 78 
"Constitue un traitement de données à caractère personnel toute opération ou tout ensemble
d’opérations portant sur de telles données, quel que soit le procédé utilisé, et notamment la
collecte, l’enregistrement, l’organisation, la conservation, l’adaptation ou la modification,
l’extraction, la consultation, l’utilisation, la communication par transmission, diffusion ou toute
autre forme de mise à disposition, le rapprochement ou l’interconnexion, ainsi que le
verrouillage, l’effacement ou la destruction." 
en rayant "a caractère personnel" ça marche encore ... ;-)

le seul bon conseil ici étant Documentez! 

Donc si on stocke de ma m....e , il qu'on sache que c'en est ...
