### ISSUE TITLE
Périmètre des "Meilleures Pratiques"

### ISSUE THREAD

**Issue by HadrienG2** [DISIC/politique-de-contribution-open-source#39]
La section "Meilleures Pratiques" me semble parfois s'écarter un peu de la question de la politique open-source, et discuter de bonnes pratiques de développement logiciel en général. Par exemple, les pratiques de sécurité concernent tout le monde, même si l'open-source a des avantages et inconvénients spécifiques à ce niveau.

Je n'ai en soi absolument rien contre inclure de telles informations, mais je me demandais si il n'y aurait pas quelque part un autre document davantage concentré sur les bonnes pratiques de développement logiciel dans l'absolu, auquel cas ces recommandations pourraient y être incluses et la politique open-source serait alors modifiée pour y faire référence.

A moins bien sûr que le plan ne soit de déclarer qu'en tant qu'organisme orienté vers le service public, l'Etat se doit de publier tous ses codes en open-source, ce qui me surprendrait agréablement... mais je doute que des organismes comme le CEA ou la DGS[E|I] laisseraient passer une telle clause 😄

**Comment by bzg** [comment]
> A moins bien sûr que le plan ne soit de déclarer qu'en tant qu'organisme orienté vers le service public, l'Etat se doit de publier tous ses codes en open-source

De ce que je comprends, la loi pour une République numérique va bien [dans ce sens](https://www.alain-bensoussan.com/avocats/code-source-document-administratif/2016/05/19/).

Je vois un problème plus large: je crois qu'il faudrait distinguer les recommandations à destinations des développeurs/mainteneurs de logiciels libres dans l'administration et celles à destination des contributeurs.

Côté développeurs, ces bonnes pratiques sont utiles, à condition effectivement de préciser que certaines valent pour tout logiciel, libre ou non. J'y ajouterai la nécessité d'avoir un système de suivi de bugs et une liste de tâches faciles à prendre en main pour des contributeurs occasionnels.

Côté contributeurs, j'ajouterais en vrac: la description d'un bon rapport de bug ("ce que j'espérais" => "ce que j'ai fait" => "ce qui a eu lieu" => "comment reproduire ce bug avec un exemple minimal") ; le fait de lire les échanges sur les listes et les forums avant d'y participer (une semaine est un bon délai).

Mais ça demande une grosse restructuration des documents - à discuter avant.

**Comment by ljoubert** [comment]
Je suis d'accord avec vous sur le fait de pointer vers un document de référence sur les bonnes pratiques de développement. Pour la partie sécurité, nous pourrons pointer vers des documents de l'ANSSI quand ils seront disponibles.

Dans le cadre de cette politique, la question est de savoir s'il y a des bonnes pratiques qui ressortent spécifiquement du fait de l'ouverture et qui pourraient être mis en exergue.

Je vous confirme que la loi République Numérique va bien dans ce sens avec les trois exceptions suivantes:
* sécurité des SI et des personnes
* propriété intellectuelle de tiers
* faciliter le contournement de système anti-fraude

**Comment by ljoubert** [comment]
Proposition de suivre la discussion sur les référentiels généraux dans #56 et les aspects simplification sur les bonnes pratiques de développement et de sécurité spécifiques dans #55
