### ISSUE TITLE
FAQ ?

### ISSUE THREAD

**Issue by camillem** [DISIC/politique-de-contribution-open-source#44]
Bonjour, 

Il pourrait être intéressant d'accompagner la politique d'une faq, qui permettrait d'en expliciter certains points sans alourdir le texte en lui-même.

**Comment by bzg** [comment]
Oui, tout à fait d'accord.

**Comment by revolunet** [comment]
une première question pourrait être : "comment choisir parmi les différentes licences proposées" ? 

ex: Apache VS MIT ?

guide anglophone associé : https://choosealicense.com/

**Comment by revolunet** [comment]
Une autre question : "doit-on utiliser son email pro pour contribuer à un projet open-source tiers sur lequel nous contribuons historiquement avec notre compte perso" ?

**Comment by ljoubert** [comment]
Très bonne idée :) Je vous propose d'itérer en PR sur la page faq.md. Pour l'instant je n'ai initié que les 3 questions.
