### ISSUE TITLE
Contributions hors code

### ISSUE THREAD

**Issue by camillem** [DISIC/politique-de-contribution-open-source#45]
Bonjour, 
Serait-il pertinent dans le cadre de cette politique d'aborder les contributions hors code, comme la participation sur les différents canaux de discussion d'un projet ?

Voir par exemple : https://opensource.guide/how-to-contribute/#you-dont-have-to-contribute-code

**Comment by bzg** [comment]
Oui, je trouve que ça serait pertinent. Voir aussi [cette remarque](https://github.com/DISIC/politique-de-contribution-open-source/issues/39#issuecomment-353048951) sur la question générale du périmètre du document.

**Comment by jfcjm** [comment]
Inclure aussi ce qui touche à la loclaisation/internationalisation des logiciels?

**Comment by ljoubert** [comment]
Je ne suis pas sûr de comprendre la question. Il faudrait explicitement rajouter à la politique de contribution que la pré-autorisation de contribuer du code va avec la pré-autorisation de pouvoir en discuter publiquement ?

Ou pour être pragmatique, dire que poser des questions sur stackoverflow avec son mail pro est autorisé de la même manière que de contribuer à github avec son mail pro?

Est-ce que cela ne relèverait pas plutot d'une politique de bon usage des réseaux sociaux ? (@bzg je distingue la partie documentation du code)

@jfcjm sur la partie localisation/internationalisation quelle est la question ? Explicitement dire qu'il est autorisé de coder en anglais si on souhaite toucher une population de développeurs à l'international ? Demander à avoir une documentation en anglais et en français ?

**Comment by bzg** [comment]
> Serait-il pertinent dans le cadre de cette politique d'aborder les contributions hors code, comme la participation sur les différents canaux de discussion d'un projet ?

Je pense que cela mérite une petite section dans `pratique.md` autour des bonnes pratiques de communication. @camillem tu serais partant pour rédiger un petit paragraphe?

**Comment by bzg** [comment]
Bonjour @camillem : la 1.1 est sortie, n'hésite pas à commencer ce paragraphe dans une PR pour une future 1.2 qu'on pourrait sortir en juin 2020.  Merci !

**Comment by bzg** [comment]
Pas de retour depuis longtemps : à garder en tête au moment de la rédaction des guides logiciels libres d'Etalab (guides.etalab.gouv.fr).
