### ISSUE TITLE
et la documentation ?

### ISSUE THREAD

**Issue by krominet** [DISIC/politique-de-contribution-open-source#46]
je suis tombé sur des cas ou les développeurs excluent la documentation de la licence libre de leur développements ... exemples, pré-requis, contexte etc ...
pour eux c'est voilà le code et débrouilles-toi !

en serait-il de même des développements "publics" ?
sommes nous en contexte Licences Open Source, ou Licences Libres (les exemples cités en liminaire)?

**Comment by camillem** [comment]
La documentation est, en effet, un aspect crucial des projets et, hélas, souvent négligée. 
La présente politique dans son état actuelle mentionne déjà : 

> Documenter, hors du code et des commentaires
>     l’architecture logicielle du projet (i.e. découpage en modules fonctionnels et/ou avec des privilèges particuliers)
>     les interfaces exposées par chaque module, la nature et le format des informations échangées/stockées
>     les processus d’installation, de configuration et de mise en production
> 


https://disic.github.io/politique-de-contribution-open-source/pratique/#bonnes-pratiques-de-d%C3%A9veloppement

Concernant les licences pour les nouveaux projets, elles sont listées à l'adresse :  http://www.data.gouv.fr/fr/licences
Comme vous pouvez le constater, elles sont toutes reconnues conformes à la fois à la _Free Software Definition_ par la FSF et à l'_Open Source Definition_ par l'Open Source Initiative.

**Comment by ljoubert** [comment]
Je vous rejoins sur la partie documentation. Cet aspect peut effectivement être plus développé. A priori la documentation disponible du logiciel devrait être mise à disposition sous licence ouverte 2.0 avec le code source.

**Comment by bzg** [comment]
La version actuelle contient quelques éléments.
