### ISSUE TITLE
RGPD et plateformes non européennes.

### ISSUE THREAD

**Issue by Dan33l** [DISIC/politique-de-contribution-open-source#48]
Dans `pratique.md` il y est listé un certain nombre de plateformes dont certaines ne sont pas dans l'espace européen.

Or, l'arrivée en mai 2018 du Règlement Général sur le Protection des Données (alias RGPD) impose que le donneur d'ordre s’assure du respect du règlement pour ses sous-traitants. 

RGPD article 4 en vigueur en mai 2018 : 
http://eur-lex.europa.eu/legal-content/FR/TXT/HTML/?uri=CELEX:32016R0679&from=FR

> «données à caractère personnel», toute information se rapportant à une personne physique identifiée ou identifiable (ci-après dénommée «personne concernée»); est réputée être une «personne physique identifiable» une personne physique qui peut être identifiée, directement ou indirectement, notamment par référence à un identifiant, tel qu'un nom, un numéro d'identification, des données de localisation, un identifiant en ligne, ou à un ou plusieurs éléments spécifiques propres à son identité physique, physiologique, génétique, psychique, économique, culturelle ou sociale;

Loi informatique et libertés article 35 en vigueur en mai 2018 : 
https://www.legifrance.gouv.fr/affichTexte.do;jsessionid=4B84F0488CAE26AB4E5BEC84F101F724.tplgfr31s_2?cidTexte=LEGITEXT000006068624&dateTexte=20180525#LEGIARTI000006528134

> Toute personne traitant des données à caractère personnel pour le compte du responsable du traitement est considérée comme un sous-traitant au sens de la présente loi.

RGPD article 28 en vigueur en mai 2018 : 
http://eur-lex.europa.eu/legal-content/FR/TXT/HTML/?uri=CELEX:32016R0679&from=FR
> Lorsqu'un traitement doit être effectué pour le compte d'un responsable du traitement, celui-ci fait uniquement appel à des sous-traitants qui présentent des garanties suffisantes quant à la mise en œuvre de mesures techniques et organisationnelles appropriées de manière à ce que le traitement réponde aux exigences du présent règlement et garantisse la protection des droits de la personne concernée.

Prenons l'exemple de la plateforme github, il y est impossible de supprimer un ticket. Ce ticket, ici présent, est lié à mon pseudo, mes nom et prénom sont à la portée d'un clic de souris. Pour autant, ce ticket n'est pas effaçable sauf à effacer le projet entier.

N'est-ce pas mettre les responsables de traitements publics dans une situation potentiellement hors la loi que d'utiliser les plateformes qui n'ont aucunes obligations relatives au règlement européen ?
  
 (Je m'exprime au nom de [l'ADULLACT](http://adullact.org), mon employeur.)

**Comment by ljoubert** [comment]
Proposition de reprendre les discussions sur le thème RGPD de l'issue #52

**Comment by ljoubert** [comment]
#52

**Comment by ljoubert** [comment]
D'un point de vue très pragmatique, la contribution de code source en tant que logiciel libre est publique et cette politique ne s'intéresse pas aux dépôts privés. Je ne fais pas de lien direct entre le traitement des données personnelles des plateformes et le RGPD et le fait de contribuer (et de signer votre contribution via le DCO comme cela est recommandé) implique que vous acceptez que votre contribution soit publique. 

Si vous pensez au droit de retrait et de repentir, rien n’empêche une plateforme d'un pays étranger qui ne reconnait pas le droit moral de recopier le code source déjà contribué avec les difficultés que cela va entraîner. Rien de nouveau avec l RGPD.

Je veux bien un point de vue de juriste sur cet aspect si certains lisent ce commentaire.

Dans le choix d'une plateforme de service de gestion de source, un critère peut effectivement être le lien avec les dépôts privés et l'intérêt de les avoir hébergés en France.

Je ne veux pas présager des choix qui seront faits par les administrations, mais je doute que les plateformes publiques soient leur dépôt principal. Je m'attends plutôt à des git privés, probablement hébergées par l'administration elle-même, qui poussera vers la plateforme de service de son choix en fonction de la communauté visée. A noter que des réflexions sont en cours pour proposer une plateforme de référence "DINSIC" pour les dépôts privés des administrations qui n'en disposerait pas déjà.

**Comment by bzg** [comment]
Je me propose de prendre la suite pour trouver un conseil juridique sur la question.

**Comment by bzg** [comment]
Voici les informations qui m'ont été transmises par notre département juridique (je retranscris librement, les erreurs sont miennes).

Depuis le 1er août 2016 le Privacy Shield est entré en vigueur aux USA. Ce « bouclier » permetaux entreprises américaines de s’auto-certifier conformes au RGPD en s’inscrivant sur le registre de l’administration américaine. Il permet de garantir un droit de limitation, d’opposition, d’accès et de rectification aux données à caractère personnel et il est censé mettre en œuvre des dispositifs de protection adéquats.

Pour le rapport entre GitHub et le Privacy Shield: https://help.github.com/en/github/site-policy/global-privacy-practices

Pour vérifier que la certification de GitHub est active: https://www.privacyshield.gov/participant?id=a2zt000000001K2AAI

Rien ne s'oppose juridiquement à ce qu'une administration propose à ses agents d'utiliser GitHub comme plateforme de publication de ses dépôts publics.

La politique de contributions aux logiciels libres de l'Etat ancre le principe d'un choix autonome de chaque organisme public en fonction de ses besoins: certains iront sur la forge publique de l'Adullact (peut-être confortés par l'actuelle convention entre la DINUM et l'Adullact), d'autres iront sur un compte d'organisation GitLab ou GitHub.

N'hésitez pas à rouvrir le ticket si vous pensez qu'il y a encore une incertitude juridique.
