### ISSUE TITLE
Page Meilleures pratique : remarque globale

### ISSUE THREAD

**Issue by mfaure** [DISIC/politique-de-contribution-open-source#51]
Remarque globale : la page semble assez orientée dans ses exemples vers l'utilisation du service en ligne américain Github (solution propriétaire), au détriment d'autres solutions qui elles sont libres comme [Gitlab](https://en.wikipedia.org/wiki/GitLab) ou [Phabricator](https://en.wikipedia.org/wiki/Phabricator).

(Je m'exprime au nom de l'[ADULLACT](www.adullact.org/), mon employeur.)

**Comment by ljoubert** [comment]
Pouvez-vous préciser à quel endroit exactement ? Je vous invite à compléter avec d'autres solutions et services de références. Je n'ai pas trouvé de service en ligne basé sur Phabricator et Phacility ne propose pas de plan gratuit pour des projets libres.

**Comment by bzg** [comment]
Question restée sans réponse. @mfaure n'hésite pas à donner suite en réouvrant le ticket si besoin.
