### ISSUE TITLE
Meilleures pratiques > Aide au choix de la licence

### ISSUE THREAD

**Issue by mfaure** [DISIC/politique-de-contribution-open-source#54]
La Politique de Contribution au Logiciel Libre sera reprise par d'autres services publiques comme les collectivités. Dans ce contexte on ne peut pas s'isoler de la langue française (cf discussion [licences et loi Toubon](https://github.com/DISIC/politique-de-contribution-open-source/issues/32#issuecomment-355050595)).

Il nous semble impératif de citer :

* dans le cas des licences permissives : la CeCILL-B,
* dans le cas des licences avec réciprocité : la famille CeCILL v2 et CeCILL-C

(Je m'exprime au nom de l'[ADULLACT](www.adullact.org/), mon employeur.)

**Comment by ljoubert** [comment]
Pour être sûr de bien comprendre cette remarque, vous faites référence à la page : http://www.data.gouv.fr/fr/licences

Les licences CeCILL v2 CeCILL-B et CeCILL-C sont bien référencées, mais effectivement par soucis d'homogénéité et pour reprendre l'identifiant SPDX normatif, le lien pointe vers les versions anglaises.

Votre demande est donc de pointer vers le texte des licences en français ?

En fait le site SPDX pointait à l'origine sur le texte en Français des licences et ils ont changé. Cf la tentative de Pull Request pour faire reconnaitre directement les licences CeCILL sur github grâce à choose a licence: https://github.com/github/choosealicense.com/pull/527 

L'optique serait de référencer chaque licence avec sa traduction au sein du référentiel SPDX: https://github.com/spdx/license-list-XML/issues/438 

J'ai pas encore eu le temps de discuter avec SPDX sur le sujet.

**Comment by bzg** [comment]
J'ai fait remonter le sujet sur la [PR](https://github.com/github/choosealicense.com/pull/527) cité par @ljoubert - wait and see.
