### ISSUE TITLE
Meilleures pratiques > Bonnes pratiques de développement

### ISSUE THREAD

**Issue by mfaure** [DISIC/politique-de-contribution-open-source#55]
Si le fait de suivre les bonnes pratiques de développement est évidemment important, le fait de "descendre trop bas dans la technique" ne semble pas adapté. Mentionner certaines pratiques plutôt que d'autres ne semble pas adapté à un document de portée générale comme la Politique de Contribution au Logiciel Libre.

De plus, il semble très important que ces bonnes pratiques soient rédigées en français.

(Je m'exprime au nom de l'[ADULLACT](www.adullact.org/), mon employeur.)

**Comment by ljoubert** [comment]
OK sur le principe. Dans la partie bonnes pratiques de développement et de sécurité qu'est ce qui vous semble à alléger et qu'est ce qui devrait être gardé dans le cadre d'un développement en mode ouvert ? Je vous propose d'initialiser une pull request pour itérer sur ce point.

**Comment by bzg** [comment]
Je suis aussi d'avis qui faut alléger ces recommandations. @mfaure @ljoubert ok pour que j'initie une nouvelle PR?

**Comment by bzg** [comment]
Bonjour @mfaure, maintenant que la 1.1 est sortie, je relance ce sujet pour voir si tu peux entamer une PR avec quelques pistes d'allégement pour la 1.2, qu'on peut programmer pour juin 2020.  N'hésite pas à avancer dans une PR.

**Comment by bzg** [comment]
Le sujet est daté.  Il est prévu de "refactoriser" cette politique de contribution open source dans les guides logiciels d'Etalab, où nous pourrons mieux gérer la frontières entre recommandations liées à l'aspect libre du projet et recommandations techniques.
