### ISSUE TITLE
Meilleures pratiques > Sécurité

### ISSUE THREAD

**Issue by mfaure** [DISIC/politique-de-contribution-open-source#56]
De même que pour les [bonnes pratiques de développement](https://github.com/DISIC/politique-de-contribution-open-source/issues/55), les préconisations de sécurité sont trop implémentatoires et peuvent être sujettes à débat (cf discussion [Conseil très contestable dans « Développement sécurisé » ](https://github.com/DISIC/politique-de-contribution-open-source/issues/36)) voire polémique, et affaiblissent le document.

Remplacer le contenu de cette section par une invitation à suivre le [RGS (Référentiel Général de Sécurité)](http://references.modernisation.gouv.fr/securite) serait une bonne option.

(Je m'exprime au nom de l'[ADULLACT](www.adullact.org/), mon employeur.)

**Comment by camillem** [comment]
Je partage votre avis sur la nécessité de ne pas trop entrer dans les détails techniques au niveau de cette politique. En revanche, je pense qu'il y a des aspects  de sécurité qui sont spécifiquement liés à l'ouverture d'un code source (sans lien avec les aspects juridiques mais avec le fait de rendre le code  public),  et qui pourraient être mentionnés ici.

**Comment by ljoubert** [comment]
Il peut être effectivement intéressant de positionner tous les documents de références : RGI, RGAA, RGS.
Plutôt que de les mettre dans la partie bonne pratique, je préconise de les positionner en introduction en document de références.

Les référentiels généraux sont des documents normatifs qui se situent à un niveau plus important qu'une partie bonne pratique.

Par contre, je vous rejoins sur le fait de pointer vers un document de références de "bonnes pratiques de développement" qui soit en dehors de la politique de contribution. Dès que celui-ci sera disponible, il pourra être directement référencé dans cette section. Comme l'indique @camillem le point important est de partager les bonnes pratiques spécifiques à un mode de développement ouvert. (pour rappel, nous avons l'objectif d'un autre document qui serait une méthodologie d'ouverture des codes sources existant)
