### ISSUE TITLE
Meilleures pratiques > ajout Accessibilité / RGAA

### ISSUE THREAD

**Issue by mfaure** [DISIC/politique-de-contribution-open-source#57]
De même que le [RGS est mentionné](https://github.com/DISIC/politique-de-contribution-open-source/issues/56), il serait de bon ton d'ajouter une invitation à suivre le [RGAA (Référentiel Général d'Accessibilité des Administrations)](http://references.modernisation.gouv.fr/accessibilite-numerique), afin d'être en conformité avec la loi République Numérique.

(Je m'exprime au nom de l'[ADULLACT](www.adullact.org/), mon employeur.)

**Comment by luceole** [comment]
+1

**Comment by ljoubert** [comment]
OK pour pointer sur tous les référentiels généraux. Je propose de clore cette issue et de tout suivre dans #56
