### ISSUE TITLE
Meilleures pratiques > ajout Interopérabilité

### ISSUE THREAD

**Issue by mfaure** [DISIC/politique-de-contribution-open-source#58]
De même que le [RGS est mentionné](https://github.com/DISIC/politique-de-contribution-open-source/issues/56) (ainsi que le [RGAA](https://github.com/DISIC/politique-de-contribution-open-source/issues/57)), il serait pertinent d'ajouter une invitation à suivre le [RGI (Référentiel Général d'Interopérabilité)](http://references.modernisation.gouv.fr/interoperabilite)

(Je m'exprime au nom de l'[ADULLACT](www.adullact.org/), mon employeur.)

**Comment by fanetk** [comment]
Bjr, Il me semble effectivement important de suivre le RGI version 2
Pour info / formats de fichiers bureautique > http://www.ploss-ra.fr/wp-content/uploads/2017/05/Note_info_RGIv2_mai2017.pdf 
(co écrit Adullact/CNLL/La Mouette et ploss-ra à l'usage des administrations et de l'ensemble de leurs usagers [quand ils recoivent un .xlsx à "remplir" par exemple]).
slts
fa

**Comment by luceole** [comment]
+1

**Comment by ljoubert** [comment]
OK pour pointer sur tous les référentiels généraux. Je propose de clore cette issue et de tout suivre dans #56
