### ISSUE TITLE
Liste des commentaires ADULLACT

### ISSUE THREAD

**Issue by mfaure** [DISIC/politique-de-contribution-open-source#59]
Voici la liste des commentaires ADULLACT sur la Politique de Contribution au Logiciel Libre.

* [RGPD et plateformes non européennes](https://github.com/DISIC/politique-de-contribution-open-source/issues/48)
* [Assertion incorrecte sur usage des licences permissives ](https://github.com/DISIC/politique-de-contribution-open-source/issues/49)
* [Recommandation de licences permissives dans le cas général ](https://github.com/DISIC/politique-de-contribution-open-source/issues/50)
* [Page Meilleures pratique : remarque globale](https://github.com/DISIC/politique-de-contribution-open-source/issues/51)
* [Meilleures pratiques > Aide au choix de la plateforme ](https://github.com/DISIC/politique-de-contribution-open-source/issues/52)
* [Meilleures pratiques > Inventaire des comptes d’organisation ](https://github.com/DISIC/politique-de-contribution-open-source/issues/53)
* [Meilleures pratiques > Aide au choix de la licence ](https://github.com/DISIC/politique-de-contribution-open-source/issues/54)
* [Meilleures pratiques > Bonnes pratiques de développement ](https://github.com/DISIC/politique-de-contribution-open-source/issues/55)
* [Meilleures pratiques > Sécurité ](https://github.com/DISIC/politique-de-contribution-open-source/issues/56)
* [Meilleures pratiques > ajout Accessibilité / RGAA](https://github.com/DISIC/politique-de-contribution-open-source/issues/57)
* [Meilleures pratiques > ajout Interopérabilité ](https://github.com/DISIC/politique-de-contribution-open-source/issues/58)

**Comment by bzg** [comment]
Merci pour la liste. Je ferme cette issue pour alléger la liste des issues, chaque proposition reste ouverte.
