### ISSUE TITLE
Traduction "Developer Certificate of Origin"

### ISSUE THREAD

**Issue by camillem** [DISIC/politique-de-contribution-open-source#64]
Bonjour,
Je suis un peu mal à l'aise avec la traduction de "Developer Certificate of Origin" en "Certificat d'origine du développeur", puisqu'il ne s'agit pas d'attester de l'origine du développeur mais bien de celle de ses contributions. 
Pensez-vous qu'une des propositions suivantes serait plus adaptée ?

- "Certificat d'origine des développements"
- "Certificat d'origine des contributions"
- "Certificat d'origine à l'usage des développeurs"

Camille

**Comment by revolunet** [comment]
+1 pour "Certificat d'origine des contributions" qui a l'avantage de couvrir les contributions autres que du code

**Comment by ljoubert** [comment]
Pas facile, on voudrait en même temps que ce soit le plus près du texte d'origine. Cela revient à une déclaration sur l'honneur, on se fiche un peu des contributions et c'est celui qui fait cette déclaration qui compte, d'où le titre en anglais. On pourrait avoir "Certificat sur l'origine des contributions du développeur" comme "déclaration sur l'honneur du développeur", mais ca rallonge encore plus.

**Comment by revolunet** [comment]
Ce n'est pas forcement un "développeur" ?

**Comment by bzg** [comment]
Pourquoi pas mettre l'anglais avec entre parenthèse une traduction explicite ("Certificat d'origine des contributions du développeur"), en précisant aussi que "développeur" doit être entendu au sens large de "contributeur" ?

**Comment by camillem** [comment]
> que ce soit le plus près du texte d'origine

"Certificat d'origine à l'usage des développeurs" est la traduction quasi littérale.
