### ISSUE TITLE
« Adaptation » plutôt qu'« instanciation » ?

### ISSUE THREAD

**Issue by bzg** [DISIC/politique-de-contribution-open-source#67]
Cette remarque fait suite à une discussion IRL avec @camillem  

_Instanciation_ est un terme technique et un anglicisme: dans le contexte d'un document donnant des recommandations sur l'ouverture du code source, il risque d'être pris au pied de la lettre et/ou de donner l'impression que l'instanciation est une étape nécessaire (comme l'est par exemple la transposition d'une directive européenne en droit français).

Il s'agit plutôt pour les administrations qui en ont le besoin de produire une version _adaptée_ de ce document, pas vraiment de l'instancier.

Est-ce qu'_adapation_ conviendrait ?

**Comment by ljoubert** [comment]
Pourquoi pas mais on perd quelque peu le principe de subsidiarité. On pourrait parler de politique dérivée pour reprendre les principes d'héritage en POO qui serait plus juste, mais il faudrait trouver le verbe transitif

**Comment by bzg** [comment]
Ce qui reste gênant avec les notions d'instanciation ou de dérivation, c'est que cela suscite la question: "quels sont les invariants ?" Or... il y en a peu. Même en publiant un `.zip` sur un serveur FTP, l'administration est juridiquement dans les clous.

_Adaptation_ me paraît conserver l'idée de subsidiarité (qui est à la fois dans la définition de la politique et dans sa mise en oeuvre) tout en renforçant l'idée centrale, qui est que les administrations sont _libres d'adapter_ la politique à leurs ressources et à leurs besoins.

À voir avec les administrations pour une v2?

**Comment by bzg** [comment]
Voir https://github.com/DISIC/politique-de-contribution-open-source/pull/73

**Comment by bzg** [comment]
Juste un « bump » sur cette issue: pourquoi pas « déclinaison » ?

**Comment by bzg** [comment]
Peu d'engouement suscité autour de cette question :)  Je ferme.
