### ISSUE TITLE
Périmètre de la FAQ 

### ISSUE THREAD

**Issue by camillem** [DISIC/politique-de-contribution-open-source#68]
La FAQ doit-elle également expliciter certains choix de la politique ? Je pense par exemple à DCO vs. CLA.

**Comment by ljoubert** [comment]
Tu voudrais rajouter une question : "Pourquoi ne puis-je pas demander un CLA sur mon projet? " Je veux bien une proposition :)

**Comment by bzg** [comment]
@camillem je te laisse ajouter la question et la réponse? Merci ! cc @ljoubert pour information.

**Comment by camillem** [comment]
ack. :-)

**Comment by bzg** [comment]
Merci d'avance !

**Comment by bzg** [comment]
Hello @camillem - juste un gentle reminder :)
