### ISSUE TITLE
Dire "logiciel libre" plutôt que "logiciel open source"

### ISSUE THREAD

**Issue by bzg** [DISIC/politique-de-contribution-open-source#71]
Sans entrer dans des débats idéologiques (car en pratique, les licences recommandées sont celles de la FSF et de l'OSI), il faudrait remplacer "open source" par "libre" qui est l'expression figurant dans la loi pour une République Numérique ([article 16](https://www.legifrance.gouv.fr/affichTexteArticle.do;jsessionid=03FC6173429C8E6AF8EEB73946875922.tplgfr39s_1?idArticle=JORFARTI000033203039&cidTexte=JORFTEXT000033202746&dateTexte=29990101&categorieLien=id)).

**Comment by ljoubert** [comment]
Je propose que ces deux termes puissent être utilisés indifféremment, il n'y a pas de raison à privilégier l'un plutôt que l'autre.
