### ISSUE TITLE
Membres publics et privés d'une organisation

### ISSUE THREAD

**Issue by pachevalier** [DISIC/politique-de-contribution-open-source#88]
Je propose de recommander de rendre public son appartenance à une organisation gouvernemental. C'est important pour pouvoir être contacter. Par exemple, la plupart des membres de DISIC sont privés. On ne sait donc pas qui se cache derrière l'organisation, qui contacter, etc.

**Comment by ljoubert** [comment]
Merci beaucoup pour cette remarque intéressante. Il me parait déjà essentiel que chaque organisation dispose au moins de ses administrateurs en contacts publics afin de pouvoir les joindre pour créer de nouveaux projets au sein du dépôt.

Pour le reste cela relève aussi beaucoup de la granularité des organisations retenues et de la gouvernance en place au sein des ministères sur la gestion des comptes d'organisation et des dépots (ce qui est donc hors politique de contribution qui s'adresse aux développeurs). On pourra faire un mini-guide pour les ministères sur la gestion des comptes d'organisation.

En termes de contact, ce qui compte n'est pas d'afficher ton appartenance à une organisation, mais de pouvoir te retrouver sur un commit donné dans un projet donné, avec la possibilité de te joindre par mail non ? Pourquoi afficher tous les membres de l'organisation ?

**Comment by bzg** [comment]
C'est désormais dans la version actuelle.
