### ISSUE TITLE
distribution du code

### ISSUE THREAD

**Issue by revolunet** [DISIC/politique-de-contribution-open-source#90]
Bonsoir,

Je ne crois pas avoir vu ce point : celui de la "distribution" des packages au delà des sources ?

Outre gitlab ou github pour le code source, certains travaux/modules/données peuvent être publiées sur des plateformes tierces, registres... ex : npm, pypi, docker...

Je prends le cas d'un module JavaScript qui pourrait être partagé en open-source, il serait également distribué sur npm, et pour cela on aurait besoin de :
 - définir un "author" dans la description du package; 
 - avoir un compte npm avec les droits sur l'organisation sur laquelle on publie

quelle convention adopter ?

a priori Etalab est le premier acteur FR a avoir fait cette démarche sur npm 👍  : https://www.npmjs.com/org/etalab

**Comment by bzg** [comment]
Bonjour Julien,

oui, excellente question, je l'ai ajoutée comme "à traiter" pour la prochaine version mineure.

Merci !
