### ISSUE TITLE
Broken Link in English

### ISSUE THREAD

**Issue by mgifford** [DISIC/politique-de-contribution-open-source#97]
There is a space before the **.md** in this link here https://disic.github.io/politique-de-contribution-open-source/en/introduction/

USA 18F Open Source Policy:
https://github.com/18F/open-source-policy/blob/master/CONTRIBUTING.md

```
<li>USA 18F Open Source Policy:
                <br> <a href="https://github.com/18F/open-source-policy/blob/master/CONTRIBUTING .md">https://github.com/18F/open-source-policy/blob/master/CONTRIBUTING.md</a></li>
```

**Comment by mgifford** [comment]
Also a problem with link to Australia Digital Transformation Agency (in HTML) with an extra space:
https://www.dta.gov.au/standard/8-make-source-code-open/

**Comment by bzg** [comment]
Done, closing.
