### ISSUE TITLE
Ca serait bien en PDF

### ISSUE THREAD

**Issue by sfermigier** [DISIC/politique-de-contribution-open-source#99]
Un petit coup de `pandoc`, de `Sphinx` ou de `gitbook`, et zou... un PDF facile à lire offline.

**Comment by bzg** [comment]
Oui ! Voir https://github.com/DISIC/politique-de-contribution-open-source/pull/100/files#diff-45b0bbd51bdbae8f882b974b4b7aea74

En attendant, une version PDF est téléchargeable [ici](https://github.com/bzg/politique-de-contribution-open-source/raw/master/docs/pocos-dinsic-18052018.pdf).

**Comment by bzg** [comment]
J'ai relancé l'équipe de communication pour voir ce qu'on peut faire.
